// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezdkispebjgahamfgqax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZGtpc3BlYmpnYWhhbWZncWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTk2NjIsImV4cCI6MjA3MjUzNTY2Mn0.pS_AqQfutTPdLKIApPX-HvPYUXHNfU-Ar4TjP0UyPe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});